# Copyright Huawei Technologies Co., Ltd. 2023-2024. All rights reserved.
from atb_llm.common_op_builders.common_op_builder_manager import CommonOpBuilderManager
from atb_llm.common_op_builders.lm_head.no_parallel_lm_head_common_op_builder import NoParallelLmHeadCommonOpBuilder
from atb_llm.common_op_builders.lm_head.all_gather_lm_head_common_op_builder import AllGatherLmHeadCommonOpBuilder
from atb_llm.common_op_builders.lm_head.all_reduce_lm_head_common_op_builder import AllReduceLmHeadCommonOpBuilder


CommonOpBuilderManager.register(AllGatherLmHeadCommonOpBuilder)
CommonOpBuilderManager.register(AllReduceLmHeadCommonOpBuilder)
CommonOpBuilderManager.register(NoParallelLmHeadCommonOpBuilder)
